version: "3"
services:
    user-api:
        container_name: user-api
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: on-failure
        env_file: ./server/.env
        volumes:
            - ./server:/usr/app
            - /usr/app/node_modules